<a href="https://colab.research.google.com/github/akadas112/AI_code/blob/main/Emotion_detection.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from numpy import array
from google.colab import drive
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import  pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Flatten, Embedding, Dense, LSTM, Bidirectional
import numpy as np
 
 
drive.mount('/content/drive')
 
def listToString(s):  
    
    # initialize an empty string 
    str1 = " " 
    
    # return string   
    return (str1.join(s)) 
# Get a list of keys from dictionary which has the given value
 
def getKeysByValue(dictOfElements, valueToFind):
    listOfKeys = list()
    listOfItems = dictOfElements.items()
    for item  in listOfItems:
        if item[1] == valueToFind:
            listOfKeys.append(item[0])
    for key  in listOfKeys:
        a = key
    return  a
 
def read_corpus(corpus_file):
    documents = []
    labels = []
    with open(corpus_file, encoding='utf-8') as f:
        for line in f:
            tokens = line.strip().split()
            documents.append(tokens[1:])
            labels.append( tokens[0] )
    for i in range(len(documents)):
        documents[i] = listToString(documents[i])
 
    emotions = list(dict.fromkeys(labels))
    class_type = { i : emotions[i] for i in range(0, len(emotions) ) }
    listOfLebels = list()
    for i in range(len(labels)):
        listOfLebels.append(getKeysByValue(class_type, labels[i]))
 
 
    return documents, labels, emotions, listOfLebels
 
 
X, Y, emotions, listOfLebels = read_corpus('/content/drive/My Drive/Dataset/train.txt')

Mounted at /content/drive


In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder

# tokenization and converting words into sequence
tokenizer = Tokenizer()
tokenizer.fit_on_texts(X)
dense_train_doc = tokenizer.texts_to_sequences(X)
print(dense_train_doc)

# padding the training documents in order to make them equal length.
MAX_LENGTH =2400

padded_trai_doc = pad_sequences(dense_train_doc, maxlen=MAX_LENGTH, padding='post')

print(padded_trai_doc)
print(Y)
#print(listOfLebels)

y=np.array(Y)
print(y)


encoder=OneHotEncoder(sparse=False)
y=y.reshape((4700, 1))

y1=encoder.fit_transform(y)


# Model Declaration
VOCUB_SIZE = 20000
model = Sequential()

# embedding layer
embedding_layer = Embedding(VOCUB_SIZE, 32, input_length=MAX_LENGTH)
model.add(embedding_layer)

# Flattening Layer
# model.add(Flatten())

# LSTM Extra - for performance
model.add(LSTM(units=128))

# Bidirectional LSTM Extra
# forward_layer = LSTM(128, return_sequences=False)
# backward_layer = LSTM(128, return_sequences=False, go_backwards=True)
# model.add(Bidirectional(forward_layer, backward_layer=backward_layer))

# output layer
model.add(Dense(units=6, activation='softmax'))

model.compile(loss='categorical_crossentropy', optimizer='Rmsprop', metrics=['accuracy'])

print(model.summary())
#y=np.array(listOfLebels)
#y1=np.reshape(y, (4700,1))
#y=np.array(listOfLebels)
#print(padded_trai_doc.shape)
#print(y1.shape)
#model.fit(padded_trai_doc, Y, epochs=100, verbose=1)
model.fit(padded_trai_doc, y1,epochs=5)


[[4364, 1620, 399, 6716, 99, 1621, 1620, 399, 16, 7, 3225, 683, 138, 1090, 954, 6717, 89, 519, 6718, 955, 4365, 220, 49, 66, 228, 57, 6719, 956, 49, 357, 66, 11, 1091, 3, 4366, 6720, 57, 775, 6721, 358, 2638, 6722, 7, 657, 241, 4367, 66, 1622, 2639, 2640, 1023, 8, 2641, 6723, 208, 683, 99, 4368, 38, 1623, 208, 2641, 2639, 2146, 12, 2642, 7, 77, 6724, 208, 6725, 6726, 2643, 183, 23, 2640, 6727, 3225, 4, 3226, 955, 955, 266, 61, 6728, 374, 6729, 4369, 183, 53, 2147, 2148, 32, 102, 2639, 886, 6730, 30, 4370, 224, 10, 34, 6731, 1624, 163, 4371, 6732, 4369, 3, 6733, 62, 21, 29, 3227, 4, 6734, 4372, 2644, 6735, 157, 1832, 2645, 617, 6736, 6737, 6, 6738, 552, 3228, 617, 6739, 2149, 1625, 14, 3229, 4373, 553, 684, 4374, 617, 1832, 2645, 617, 6740, 12, 81, 335, 4375, 3230, 1620, 399, 492, 4372, 1625, 6741, 58, 446, 3, 39, 284, 89, 6742, 4376, 6743, 1833, 1625, 4375, 95, 1092, 1175, 3231, 17, 683, 138, 6744, 167, 1293, 6745, 1093, 58, 4377, 724, 3232, 163, 887, 284, 19, 658, 1441, 6746, 248, 12,

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

test_doc, yTest_label, emotions, test_classes = read_corpus('/content/drive/My Drive/Dataset/dev.txt')

yTest_label = array(yTest_label)
#print(len(yTest_label))
# tokenization and converting words into sequence
dense_test_doc = tokenizer.texts_to_sequences(test_doc)

# padding the test documents.
padded_test_doc = pad_sequences(dense_test_doc, maxlen=MAX_LENGTH, padding='post')

prediction = model.predict(padded_test_doc)
print(prediction)
#print(prediction.shape)
#for i in range(len(prediction)):
  #print(emotions[math.ceil(prediction[i])])
# print("Raw Prediction (Sigmoid Output):\n{}\n".format(prediction))


#loss, accuracy = model.evaluate(padded_test_doc, y1 )

#print('Accuracy: %.2f' % (accuracy*100))
#print("\n")
#print('loss: %.2f' % (loss*100))

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).
[[0.20118333 0.11504379 0.07515679 0.28496498 0.22622143 0.09742978]
 [0.20118333 0.11504379 0.07515679 0.28496498 0.22622143 0.09742978]
 [0.20118333 0.11504378 0.07515679 0.28496498 0.22622143 0.09742976]
 ...
 [0.20118333 0.11504378 0.07515679 0.28496498 0.22622143 0.09742978]
 [0.20118333 0.11504377 0.07515679 0.28496498 0.2262214  0.09742976]
 [0.20118333 0.11504377 0.07515679 0.28496498 0.2262214  0.09742976]]
